# Generated by Django 5.0.3 on 2024-03-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born',
            new_name='born_date',
        ),
        migrations.AddField(
            model_name='author',
            name='born_place',
            field=models.CharField(default=1978, max_length=100),
            preserve_default=False,
        ),
    ]
