# Generated by Django 5.0.3 on 2024-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_rename_born_author_born_date_author_born_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_place',
            field=models.CharField(max_length=150),
        ),
    ]
