# Generated by Django 5.0.3 on 2024-03-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_alter_author_born_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='authors',
            new_name='author',
        ),
    ]
