version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: noteapp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: noteapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
